// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgqrcdmnpuoqvveiuemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncXJjZG1ucHVvcXZ2ZWl1ZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Mjc1NTMsImV4cCI6MjA3NDIwMzU1M30.9E5_Cejwsa64GWZHlM7Clw0vBJ_Pfk0e38443ggjiVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});